# Generated by Django 4.2 on 2025-05-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='章节名称')),
                ('video_url', models.FileField(blank=True, upload_to='videos/', verbose_name='章节视频地址')),
            ],
            options={
                'verbose_name': '章节管理',
                'verbose_name_plural': '章节管理',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('introduction', models.TextField(verbose_name='简介')),
            ],
            options={
                'verbose_name': '课程管理',
                'verbose_name_plural': '课程管理',
            },
        ),
    ]
